### ISSUE TITLE
Textures not rendered

### ISSUE THREAD

**Issue by EimantasLedinauskas** [edo9300/edopro#151] opened 2020-04-13 10:16 UTC
On some of my linux machines for some reason textures are not rendered (see picture). It seems that it is related to opengl version. I tested this program on 4 different machines (3 manjaro, 1 arch) and this problem occurs on 2 of them, where the program prints "Using renderer: OpenGL 4.6" at the startup. On machines where it prints "Using renderer: OpenGL 3.0" everything works fine... Any ideas what could be the cause?

![Screenshot_2020-04-13_13-07-31](https://user-images.githubusercontent.com/13329931/79113120-d58c7e00-7d88-11ea-96fe-bc320cecb113.png)

**Comment by edo9300** [comment] 2020-04-13 11:36
This issue with the driver is pretty troublesome, expecially because we can run the client fine on manjaro + opengl 4.6, so it might be a driver issue for that specific graphics card, a thing you could try, is forcing a forced gl version to be used with the program ```MESA_GL_VERSION_OVERRIDE=3.0 ./EDOPro``` and see if it works

**Comment by EimantasLedinauskas** [comment] 2020-04-13 12:25
Tried `MESA_GL_VERSION_OVERRIDE=3.0 ./EDOPro`, but still the problem persists. Also tried adding `MESA_GLSL_VERSION_OVERRIDE=330` (because the program was printing that it still uses GLSL 4.6), but no luck either. Is it possible to turn on some kind of logging which could help in this situation?

**Comment by edo9300** [comment] 2020-04-13 14:23
Hmm, so even force setting it to 3.0 didn't work either. What graphic drivers and gpus are being used in those computers?

**Comment by edo9300** [comment] 2020-04-13 14:56
After further investigation, i think that issue is caused by the driver not workign properly with the flag ```GL_TEXTURE_COORD_ARRAY``` (maybe it's not correctly set?), in fact, if this statement is removed https://github.com/edo9300/irrlicht1-8-4/blob/master/source/Irrlicht/COpenGLDriver.cpp#L1464 , that issue is replicated 100% of the time on other devices as well 
![image](https://user-images.githubusercontent.com/18705342/79130687-a6393980-7da7-11ea-9af8-fe82b33cd5f4.png)

**Comment by EimantasLedinauskas** [comment] 2020-04-13 17:09
Here is some info about one of the GPUs (I can't access the other machine for now):

>  Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 5500 (BDW GT2) (0x1616)
    Version: 20.0.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
    OpenGL vendor string: Intel
    OpenGL renderer string: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
    OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.4
    OpenGL core profile shading language version string: 4.60
    OpenGL core profile context flags: (none)
    OpenGL core profile profile mask: core profile
    OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.0.4
    OpenGL shading language version string: 4.60
    OpenGL context flags: (none)
    OpenGL profile mask: compatibility profile
    OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.0.4
    OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by feuerpanda** [comment] 2020-04-16 14:05
Can replicate on Arch based distros. 

I tried to replicate on OpenSUSE and several Debian/Ubuntu distros, but it doesnt happen there.

**Comment by kevinlul** [comment] 2020-04-24 04:06
Confirmed cases:
- Lenovo thinkpad T450, Arch Linux, kernel 5.6.4-arch1-1

- ![Arch](https://media.discordapp.net/attachments/578544956415803405/703093764243062794/2020-04-24-070324_688x352_scrot.png)

**Comment by kevinlul** [comment] 2020-04-24 04:21
From `Hope#7910`:
mesa 20.0.4 -> 20.0.5 introduces the regression

**Comment by HopeBaron** [comment] 2020-04-24 04:59
> From `Hope#7910`:
> mesa 20.0.4 -> 20.0.5 introduces the regression, using OpenGL 4.5

Right, switching back downgrading fixed my issue.
As for the original issue, it seems like OpenGL 4.6 is the package causing the issue downgrading it will fix the issue. Not sure, but maybe the `20.0.5` works with that version of OpenGL

**Comment by FelixRilling** [comment] 2020-04-25 12:35
I can reproduce this issue on archlinux with mesa 20.0.5-1, xorg-server 1.20.8-1.
downgrading to mesa 20.0.4-2 fixes the issue.

**Comment by FelixRilling** [comment] 2020-04-30 06:30
Updating to mesa-20.0.6-1 fixed the issue as well.

**Comment by edo9300** [comment] 2020-04-30 10:41
> Updating to `mesa-20.0.6-1` fixed the issue as well.

So maybe this regression got fixed in the new version. @EimantasLedinauskas, @feuerpanda , @HopeBaron could you check if this issue is fixed on your end as well with the driver update?

**Comment by EimantasLedinauskas** [comment] 2020-04-30 12:11
> > Updating to `mesa-20.0.6-1` fixed the issue as well.
> 
> So maybe this regression got fixed in the new version. @EimantasLedinauskas, @feuerpanda , @HopeBaron could you check if this issue is fixed on your end as well with the driver update?

Yes, the issue disappeared with the new mesa version for me too.

**Closed** 2020-04-30 22:16 UTC
Labels: bug, linux

**Comment by deus369** [comment] 2022-10-27 01:02
i have this issue with basic opengl texturing :O this post made me realize it might be the drivers. It works on my Pinephone Pro and not my pc with nvidia.
